apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
data:
  DB_PASSWORD: YWRtaW4xMjM0 # admin1234
type: Opaque

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: 517121893325.dkr.ecr.us-east-1.amazonaws.com/backend:1.0   
        name: backend
        ports:
        - containerPort: 80
        env:
        - name: DB_USERNAME
          value: admin
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: DB_PASSWORD
        - name: DB_ENDPOINT
          value: database-service
        - name: DB_NAME
          value: reviews-db