apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: 517121893325.dkr.ecr.us-east-1.amazonaws.com/backend:1.0
        name: backend
        ports:
        - containerPort: 80
