apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
data:
  DB_USERNAME: YWRtaW4= # admin
  DB_PASSWORD: dXNlcl9wYXNzd29yZA== # user_password
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/reviews-backend:latest
          name: backend
          ports:
            - containerPort: 80
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: DB_ENDPOINT
              value: database-service
            - name: DB_NAME
              value: reviews_db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: backend-service
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: backend
  type: LoadBalancer
