apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZAo= # root_password
  MYSQL_PASSWORD: dXNlcl9wYXNzd29yZAo= # user_password
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy: {}
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: 401413892014.dkr.ecr.us-east-1.amazonaws.com/reviews-database:latest
          name: database
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: reviews-db
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: MYSQL_PASSWORD
